class ZCX_AUTORIZACION_ALFA10 definition
  public
  inheriting from CX_STATIC_CHECK
  create public .

public section.

  constants ZCX_AUTORIZACION_ALFA10 type SOTR_CONC value '000C292775F91EDF8EAB74EE1BFCC96B' ##NO_TEXT.
  constants USUARIO_INACTIVO type SOTR_CONC value '000C292775F91EDF8EB1AB38426C8FA1' ##NO_TEXT.

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_AUTORIZACION_ALFA10 IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
 IF textid IS INITIAL.
   me->textid = ZCX_AUTORIZACION_ALFA10 .
 ENDIF.
  endmethod.
ENDCLASS.
